// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// rsymbolic2_r.cpp
cpp11::writable::list symbolic_regression_cpp(cpp11::doubles_matrix<> X, cpp11::doubles  y, int             population_size, int             generations, int             tournament_size, cpp11::strings  unary_ops, cpp11::strings  binary_ops, int             max_depth, int             max_nodes, double          target_loss, bool            simplify, double          crossover_probability, double          seed, int             n_populations, double          timeout_seconds, int             verbosity, double          optimize_probability, double          parsimony, double          adaptive_parsimony_scaling, double          tournament_selection_p, bool            should_optimize_constants, double          fraction_replaced_hof, cpp11::doubles  mutation_weights, std::string     model_selection, double          max_evals, double          early_stop_condition, cpp11::doubles  weights, bool            batching, int             batch_size, double          warmup_maxsize_by);
extern "C" SEXP _rsymbolic2_symbolic_regression_cpp(SEXP X, SEXP y, SEXP population_size, SEXP generations, SEXP tournament_size, SEXP unary_ops, SEXP binary_ops, SEXP max_depth, SEXP max_nodes, SEXP target_loss, SEXP simplify, SEXP crossover_probability, SEXP seed, SEXP n_populations, SEXP timeout_seconds, SEXP verbosity, SEXP optimize_probability, SEXP parsimony, SEXP adaptive_parsimony_scaling, SEXP tournament_selection_p, SEXP should_optimize_constants, SEXP fraction_replaced_hof, SEXP mutation_weights, SEXP model_selection, SEXP max_evals, SEXP early_stop_condition, SEXP weights, SEXP batching, SEXP batch_size, SEXP warmup_maxsize_by) {
  BEGIN_CPP11
    return cpp11::as_sexp(symbolic_regression_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles_matrix<>>>(X), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles >>(y), cpp11::as_cpp<cpp11::decay_t<int            >>(population_size), cpp11::as_cpp<cpp11::decay_t<int            >>(generations), cpp11::as_cpp<cpp11::decay_t<int            >>(tournament_size), cpp11::as_cpp<cpp11::decay_t<cpp11::strings >>(unary_ops), cpp11::as_cpp<cpp11::decay_t<cpp11::strings >>(binary_ops), cpp11::as_cpp<cpp11::decay_t<int            >>(max_depth), cpp11::as_cpp<cpp11::decay_t<int            >>(max_nodes), cpp11::as_cpp<cpp11::decay_t<double         >>(target_loss), cpp11::as_cpp<cpp11::decay_t<bool           >>(simplify), cpp11::as_cpp<cpp11::decay_t<double         >>(crossover_probability), cpp11::as_cpp<cpp11::decay_t<double         >>(seed), cpp11::as_cpp<cpp11::decay_t<int            >>(n_populations), cpp11::as_cpp<cpp11::decay_t<double         >>(timeout_seconds), cpp11::as_cpp<cpp11::decay_t<int            >>(verbosity), cpp11::as_cpp<cpp11::decay_t<double         >>(optimize_probability), cpp11::as_cpp<cpp11::decay_t<double         >>(parsimony), cpp11::as_cpp<cpp11::decay_t<double         >>(adaptive_parsimony_scaling), cpp11::as_cpp<cpp11::decay_t<double         >>(tournament_selection_p), cpp11::as_cpp<cpp11::decay_t<bool           >>(should_optimize_constants), cpp11::as_cpp<cpp11::decay_t<double         >>(fraction_replaced_hof), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles >>(mutation_weights), cpp11::as_cpp<cpp11::decay_t<std::string    >>(model_selection), cpp11::as_cpp<cpp11::decay_t<double         >>(max_evals), cpp11::as_cpp<cpp11::decay_t<double         >>(early_stop_condition), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles >>(weights), cpp11::as_cpp<cpp11::decay_t<bool           >>(batching), cpp11::as_cpp<cpp11::decay_t<int            >>(batch_size), cpp11::as_cpp<cpp11::decay_t<double         >>(warmup_maxsize_by)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_rsymbolic2_symbolic_regression_cpp", (DL_FUNC) &_rsymbolic2_symbolic_regression_cpp, 30},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_rsymbolic2(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
