// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// symbolic_regression_cpp
List symbolic_regression_cpp(NumericMatrix X, NumericVector y, int population_size, int generations, int tournament_size, CharacterVector unary_ops, CharacterVector binary_ops, int max_depth, int max_nodes, double target_loss, bool simplify, double crossover_probability, double seed, int n_populations);
RcppExport SEXP _rsymbolic2_symbolic_regression_cpp(SEXP XSEXP, SEXP ySEXP, SEXP population_sizeSEXP, SEXP generationsSEXP, SEXP tournament_sizeSEXP, SEXP unary_opsSEXP, SEXP binary_opsSEXP, SEXP max_depthSEXP, SEXP max_nodesSEXP, SEXP target_lossSEXP, SEXP simplifySEXP, SEXP crossover_probabilitySEXP, SEXP seedSEXP, SEXP n_populationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type population_size(population_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type generations(generationsSEXP);
    Rcpp::traits::input_parameter< int >::type tournament_size(tournament_sizeSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type unary_ops(unary_opsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type binary_ops(binary_opsSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< int >::type max_nodes(max_nodesSEXP);
    Rcpp::traits::input_parameter< double >::type target_loss(target_lossSEXP);
    Rcpp::traits::input_parameter< bool >::type simplify(simplifySEXP);
    Rcpp::traits::input_parameter< double >::type crossover_probability(crossover_probabilitySEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n_populations(n_populationsSEXP);
    rcpp_result_gen = Rcpp::wrap(symbolic_regression_cpp(X, y, population_size, generations, tournament_size, unary_ops, binary_ops, max_depth, max_nodes, target_loss, simplify, crossover_probability, seed, n_populations));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rsymbolic2_symbolic_regression_cpp", (DL_FUNC) &_rsymbolic2_symbolic_regression_cpp, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_rsymbolic2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
