# Generated by cpp11: do not edit by hand

symbolic_regression_cpp <- function(X, y, population_size, generations, tournament_size, unary_ops, binary_ops, max_depth, max_nodes, target_loss, simplify, crossover_probability, seed, n_populations, timeout_seconds, verbosity, optimize_probability, parsimony, adaptive_parsimony_scaling, tournament_selection_p, should_optimize_constants, fraction_replaced_hof, mutation_weights, model_selection, max_evals, early_stop_condition, weights) {
  .Call(`_rsymbolic2_symbolic_regression_cpp`, X, y, population_size, generations, tournament_size, unary_ops, binary_ops, max_depth, max_nodes, target_loss, simplify, crossover_probability, seed, n_populations, timeout_seconds, verbosity, optimize_probability, parsimony, adaptive_parsimony_scaling, tournament_selection_p, should_optimize_constants, fraction_replaced_hof, mutation_weights, model_selection, max_evals, early_stop_condition, weights)
}
