# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

symbolic_regression_cpp <- function(X, y, population_size, generations, tournament_size, unary_ops, binary_ops, max_depth, max_nodes, target_loss, simplify, crossover_probability, seed, n_populations, timeout_seconds, verbosity, optimize_probability, parsimony) {
    .Call(`_rsymbolic2_symbolic_regression_cpp`, X, y, population_size, generations, tournament_size, unary_ops, binary_ops, max_depth, max_nodes, target_loss, simplify, crossover_probability, seed, n_populations, timeout_seconds, verbosity, optimize_probability, parsimony)
}

